import type { Metadata } from "next";
import "./globals.css";
import { Hind_Siliguri } from "next/font/google";
import BackToTop from "../shared/BackToTop/BackToTop";
import Header from "../shared/Header/Header";
import Footer from "../shared/Footer/Footer";
import { Toaster } from "react-hot-toast";

const siliguri = Hind_Siliguri({
  weight: "400",
  subsets: ["bengali"],
});

export const metadata: Metadata = {
  title: "Craft Institute BD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${siliguri.className} antialiased`}>
        {/* <SubHeader /> */}
        <Header />
        {children}
        <Toaster />
        <BackToTop />
        <Footer />
      </body>
    </html>
  );
}
