import type { Metadata } from "next";
import "./globals.css";
import { Hind_Siliguri } from "next/font/google";
import BackToTop from "../shared/BackToTop/BackToTop";
import Header from "../shared/Header/Header";
// import SubHeader from "../shared/SubHeader/SubHeader";
import Footer from "../shared/Footer/Footer";

const siliguri = Hind_Siliguri({
  weight: "400",
  subsets: ["bengali"],
});



export const metadata: Metadata = {
  title: "Craft Institute BD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${siliguri.className} antialiased`}
      >
      {/* <SubHeader /> */}
        <Header />
        {children}
        
        <BackToTop />
        <Footer/>
      </body>
    </html>
  );
}
