import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import BackToTop from "./shared/BackToTop/BackToTop";

// import SubHeader from "./shared/SubHeader/SubHeader";
// import Header from "./shared/Header/Header";
// import Footer from "./shared/Footer/Footer";
import { Hind_Siliguri } from "next/font/google";

const siliguri = Hind_Siliguri({
  weight: "400",
  subsets: ["latin"],
});


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Craft Institute BD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${siliguri.className} antialiased`}
      >
        {children}
        <BackToTop />
      </body>
    </html>
  );
}
